### ISSUE TITLE
Windows: Trojan Detected

### ISSUE THREAD

**Issue by djarbz** [bdd/runitor#175]
I imagine a false-positive...

Trojan:Win32/Commandrob.A!ml

CmdLine: C:\ASSETS\Tools\runitor-v1.2.0-build.2-windows-amd64.exe ...

**Comment by bdd** [comment]
Searched about the malware naming. I'm guessing it's Windows Defender that gave this. Turns out that `!ml` at the end is an indicator for machine learning, more specifically attributed to their [use of ML.NET](https://dotnet.microsoft.com/en-us/platform/customers/microsoft-defender).

Runitor is a command runner which eventually calls out to external service to relay that command's output and exit status. So, it's not surprising it may get flagged as suspicious, but on the other hand it's disappointing for a company $3T company going around chest thumping about their AI advancements to derive such low effort heuristics and lead to false positives.

I doubt this is something I can address easily.

**Comment by djarbz** [comment]
Thanks for looking into this.
